### PR TITLE
[WIP] Playlist Functionality

### PR DESCRIPTION
**Pull request by defvs**
Add songs to a playlist and listen to music continuously without needing to choose a song when one ends !

Design TODOs :

- [x] Add replay and random options
- [ ] Right click context menu in both Catalog and Playlist tabs
- [ ] More columns in the playlist
- [ ] Indicate which song is playing in the playlist
- [ ] Drag & Drop for playlist sorting
- [ ] (Linked to #3) Inform the user about the playlist
- [ ] (Linked to #5) Add icons for repeat and shuffle, both On an Off states

Code TODOs :

- [X] Reformat code to match the repo
- [x] Make the code smaller by using all Kotlin possibilities

### CODE REVIEW

**Comment by defvs** [comment]
Make sure to merge #2 before this one. As I merged my master branch into this one, #2 is included in it as well.

**Comment by Xerus2000** [comment]
Hmm, you usually should not base PRs off each other unless there's a dependency, but whatever. I'll take care of the other PR shortly, I'm still cleaning out the repo and history locally.

**Comment by Xerus2000** [comment]
The commit message for the last commit is not good. You should not put thoughts and todos into commit messages, only the actual changes. Everything else belongs into PRs and Issues.
I'd suggest you ammend it and change the message simply to "Add Playlist functionality". Most features are unpretty in the beginning anyways.

**Comment by defvs** [comment]
It is highly discouraged to forcepush, which is needed for me to rebase this old commit. See https://help.github.com/articles/changing-a-commit-message/

**Pull request closed without merging**
