### PR TITLE
feat(downloader): add option to enable download dirs variables individually

### LINKED ISSUE #84: downloader : Variables doesn't work in "Singles Subfolder"
I'd love having that feature to have one folder per single so I can store the separate album art and not mess up my Player which is dumb and grabs the cover applying it to every other sing in the folder if they are all on root...

Also I know nothing about your variable things, I'll try to have a look later.

### PR DESCRIPTION
**Pull request by defvs**
Fixes #84

### CODE REVIEW

**Comment by Xerus2000** [comment]
no. To disable them simply leave the textfield blank.

**Comment by defvs** [comment]
What if I want to use a directory like "Singles" to store all my singles ?

**Comment by Xerus2000** [comment]
put "Singles" into the textfield?

**Comment by defvs** [comment]
Yeah you're right. Also what about if I want something like "Singles/%whatever%/" ? The function removes the "/" (or "\" on windows). Do you think it's better to move the check/replace to the variables instead of the whole string ?

**Comment by Xerus2000** [comment]
create an issue for it, I'll look

**Pull request closed without merging**
