### PR TITLE
Close the output file so it can be renamed as intended.

### PR DESCRIPTION
**Pull request by Shinisuryu**
Friend suggested I should make a pull request. #34

### CODE REVIEW

**Comment by Xerus2000** [comment]
Thank you very much!

I am not merging this, because I will solve the issue in another way, but you finally pointed me to the solution of a a very important issue and I really appreciate this :)

**Comment by Shinisuryu** [comment]
Awesome! That's exactly why I didn't want to at first, but said friend pointed out it could just be closed.

**Comment by Xerus2000** [comment]
That friend was right :) opening a PR is almost always a greater help than just opening an issue, even if it doesn't get merged in the end, since it communicates valuable information about the root of the issue.

The bug is now fixed and I'll publish a new version - please do try it and always report any problems you encounter. ;)

**Comment by Shinisuryu** [comment]
Gotcha, still a bit inexperienced with stuff like this. I will though!

**Pull request closed without merging**
